name: Lint

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  super-linter:
    name: Super Linter
    uses: harryzcy/github-actions/.github/workflows/linter.yml@8b5eecdfeccfc9598d7d5ffd0139afbf302b68e6 # main

  readme:
    name: Correct README
    runs-on: ubuntu-26.04
    if: github.event_name == 'pull_request'
    permissions:
      pull-requests: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Generate README
        run: |
          python scripts/generate_readme.py

      - name: Ensure README is up to date
        run: |
          git diff --exit-code images/ubuntu/22.04/README.md
          git diff --exit-code images/ubuntu/24.04/README.md

  renovate:
    name: Renovate Config
    uses: harryzcy/github-actions/.github/workflows/renovate.yml@8b5eecdfeccfc9598d7d5ffd0139afbf302b68e6 # main
