name: Lint

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  super-linter:
    name: Super Linter
    uses: harryzcy/github-actions/.github/workflows/linter.yml@85bedbe7e622e280ceae018aecc4ed12955cf0d8 # main

  readme:
    name: Correct README
    runs-on: ubuntu-24.04
    if: github.event_name == 'pull_request'
    permissions:
      pull-requests: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Generate README
        run: |
          python scripts/generate_readme.py

      - name: Ensure README is up to date
        run: |
          git diff --exit-code images/ubuntu/22.04/README.md
          git diff --exit-code images/ubuntu/24.04/README.md

  renovate:
    name: Renovate Config
    uses: harryzcy/github-actions/.github/workflows/renovate.yml@85bedbe7e622e280ceae018aecc4ed12955cf0d8 # main
