name: Lint

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  super-linter:
    name: Super Linter
    uses: harryzcy/github-actions/.github/workflows/linter.yml@a0dee436184d6eeacdc042b8487c78eb3186e1cd # main

  readme:
    name: Correct README
    runs-on: ubuntu-26.04
    if: github.event_name == 'pull_request'
    permissions:
      pull-requests: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Generate README
        run: |
          python scripts/generate_readme.py

      - name: Ensure README is up to date
        run: |
          git diff --exit-code images/ubuntu/22.04/README.md
          git diff --exit-code images/ubuntu/24.04/README.md

  renovate:
    name: Renovate Config
    uses: harryzcy/github-actions/.github/workflows/renovate.yml@a0dee436184d6eeacdc042b8487c78eb3186e1cd # main
