name: Test Release

on:
  pull_request:

permissions:
  contents: read

jobs:
  test-release:
    name: Test QEMU Build
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/release.yml
